import os
import resend
from typing import List

resend.api_key = os.environ.get("RESEND_API_KEY")


def build_email_body(meeting) -> str:
    """Build a clean HTML email body from meeting notes."""
    language_label = "Amharic" if meeting.language == "am" else "English"
    date_str = meeting.created_at.strftime("%B %d, %Y at %H:%M")

    summary_html = ""
    for line in meeting.summary.split("\n"):
        line = line.strip()
        if not line:
            continue
        if line.startswith("📋") or line.startswith("✅") or line.startswith("📌"):
            summary_html += f"<h3 style='color:#4a90d9;margin-top:20px;'>{line}</h3>"
        elif line.startswith("•"):
            summary_html += f"<li style='margin:6px 0;'>{line[1:].strip()}</li>"
        else:
            summary_html += f"<p>{line}</p>"

    html = f"""
    <html>
    <body style="font-family: Arial, sans-serif; max-width: 700px; margin: auto; padding: 20px; color: #333;">
        <div style="background: #4a90d9; padding: 20px; border-radius: 8px 8px 0 0;">
            <h1 style="color: white; margin: 0;">📝 Meeting Notes</h1>
            <p style="color: #e0eeff; margin: 5px 0 0 0;">{date_str} · {language_label}</p>
        </div>
        <div style="border: 1px solid #ddd; border-top: none; padding: 24px; border-radius: 0 0 8px 8px;">
            {summary_html}
            <hr style="margin: 30px 0; border: none; border-top: 1px solid #eee;">
            <p style="color: #999; font-size: 12px;">
                This email was generated by Meeting Note Generator.
            </p>
        </div>
    </body>
    </html>
    """
    return html


def send_meeting_email(meeting, attendees: List[str], pdf_path: str = None) -> dict:
    """
    Send meeting notes email to a list of attendees using Resend.
    PDF attachment is skipped to avoid timeout on free tier.
    """
    if not resend.api_key:
        return {"success": False, "message": "Email credentials not configured."}

    if not attendees:
        return {"success": False, "message": "No attendees provided."}

    try:
        html_body = build_email_body(meeting)

        params: resend.Emails.SendParams = {
            "from": "Meeting Notes <onboarding@resend.dev>",
            "to": attendees,
            "subject": f"📝 Meeting Notes — {meeting.created_at.strftime('%B %d, %Y')}",
            "html": html_body,
        }

        resend.Emails.send(params)

        print(f"Email sent to {attendees}")
        return {
            "success": True,
            "message": f"Email sent successfully to {len(attendees)} attendee(s)."
        }

    except Exception as e:
        print("EMAIL ERROR:", str(e))
        return {"success": False, "message": f"Failed to send email: {str(e)}"}